# Generated by Django 3.0.2 on 2020-04-04 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200404_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emoji',
            name='emoji',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Beer'), (1, 'Love'), (2, 'Shit')]),
        ),
    ]
