# Generated by Django 3.0.2 on 2020-04-04 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200404_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emoji',
            name='emoji',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Beer'), (1, 'Love'), (2, 'Shit')], unique=True),
        ),
    ]
