# Generated by Django 3.0.2 on 2020-04-04 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0002_auto_20200404_2330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='pub_date',
        ),
    ]
