# Generated by Django 3.0.2 on 2020-04-04 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0004_message_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='pub_date',
        ),
    ]
