# Generated by Django 3.0.2 on 2020-04-05 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200405_0057'),
        ('sender', '0008_auto_20200405_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emojimessage',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Emojireceiver', to='main.User'),
        ),
        migrations.AlterField(
            model_name='emojimessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Emojisender', to='main.User'),
        ),
    ]
